window.allExams = window.allExams || {};
window.allExams["exam2"] = {
    id: "exam2",
    title: "Graphs and Charts Test 1",
    subtitle: "Reading Practice Test 1 (Questions 1–20)",
    badge: "읽기 (Reading)",
    description: "20가지 그래프 및 데이터 분석 실전 모의고사 1탄",
    questions: [
        { id: 1, title: "1. 다음은 외국인 근로자들의 국적을 조사한 결과입니다. 설명으로 맞는 것은 무엇입니까?", topic: "자기소개 (Self-Introduction)", chartType: "pie", unit: "%", data: { labels: ['베트남', '필리핀', '네팔', '캄보디아'], values: [35, 25, 20, 20] }, options: [ "베트남 사람이 가장 많습니다.", "네팔 사람이 필리핀 사람보다 많습니다.", "캄보디아 사람이 가장 적습니다.", "필리핀과 네팔 사람의 비율은 같습니다." ], answer: 0, explanation: "베트남 사람이 35%로 가장 많습니다." },
        { id: 2, title: "2. 다음은 사무실에서 자주 사용하는 물건에 대한 조사입니다. 설명으로 맞는 것은 무엇입니까?", topic: "생활용품 (Office Items)", chartType: "bar", unit: "%", data: { labels: ['컴퓨터', '의자', '책상', '프린터'], values: [45, 20, 25, 10] }, options: [ "프린터가 가장 많이 사용됩니다.", "컴퓨터가 가장 많이 사용됩니다.", "의자가 책상보다 많이 사용됩니다.", "책상이 절반 이상입니다." ], answer: 1, explanation: "컴퓨터가 45%로 가장 많이 사용됩니다." },
        { id: 3, title: "3. 다음은 사람들이 자주 가는 장소를 조사한 결과입니다. 설명으로 맞는 것은 무엇입니까?", topic: "위치와 장소 (Locations & Places)", chartType: "bar", unit: "%", data: { labels: ['은행', '병원', '시장', '공원'], values: [15, 20, 35, 30] }, options: [ "은행이 가장 많습니다.", "병원이 시장보다 많습니다.", "시장이 가장 많습니다.", "공원이 가장 적습니다." ], answer: 2, explanation: "시장이 35%로 가장 많습니다." },
        { id: 4, title: "4. 다음은 하루 동안 하는 일의 시간입니다. 설명으로 맞는 것은 무엇입니까?", topic: "동작과 사물 (Daily Actions)", chartType: "bar", unit: "시간", data: { labels: ['일하기', '공부하기', '운동하기', '쉬기'], values: [8, 2, 1, 3] }, options: [ "운동하기가 가장 깁니다.", "일하는 시간이 공부하는 시간보다 짧습니다.", "쉬는 시간은 3시간입니다.", "공부하는 시간은 4시간입니다." ], answer: 2, explanation: "쉬는 시간은 3시간입니다." },
        { id: 5, title: "5. 다음은 한 주 동안 운동한 횟수입니다. 설명으로 맞는 것은 무엇입니까?", topic: "날짜와 요일 (Days & Dates)", chartType: "line", unit: "회", data: { labels: ['월', '화', '수', '목', '금', '토', '일'], values: [1, 2, 1, 3, 2, 4, 3] }, options: [ "토요일에 가장 많이 운동했습니다.", "월요일과 수요일은 같습니다.", "금요일에는 운동하지 않았습니다.", "일요일보다 목요일에 더 많이 운동했습니다." ], answer: 0, explanation: "토요일에 4회로 가장 많이 운동했습니다." },
        { id: 6, title: "6. 다음은 외국인 근로자의 하루 일과 시간입니다. 설명으로 맞는 것은 무엇입니까?", topic: "하루 일과 (Daily Routine)", chartType: "pie", unit: "%", data: { labels: ['근무', '수면', '여가', '식사'], values: [38, 33, 21, 8] }, options: [ "수면 시간이 가장 짧습니다.", "근무 시간이 수면 시간보다 깁니다.", "여가 시간이 식사 시간보다 많습니다.", "식사 시간이 여가 시간보다 많습니다." ], answer: 1, explanation: "근무 시간(38%)이 수면 시간(33%)보다 깁니다." },
        { id: 7, title: "7. 다음은 계절별 평균 기온입니다. 설명으로 맞는 것은 무엇입니까?", topic: "계절과 날씨 (Seasons & Weather)", chartType: "bar", unit: "℃", data: { labels: ['봄', '여름', '가을', '겨울'], values: [15, 28, 17, 2] }, options: [ "겨울이 가장 덥습니다.", "여름이 봄보다 따뜻합니다.", "가을이 여름보다 덥습니다.", "봄의 평균 기온은 5도입니다." ], answer: 1, explanation: "여름(28도)이 봄(15도)보다 따뜻합니다." },
        { id: 8, title: "8. 다음은 가족 구성원 수를 조사한 결과입니다. 설명으로 맞는 것은 무엇입니까?", topic: "가족과 친구 (Family & Friends)", chartType: "bar", unit: "%", data: { labels: ['1명', '2명', '3명', '4명 이상'], values: [10, 25, 40, 25] }, options: [ "1명인 가족이 가장 많습니다.", "3명인 가족이 가장 많습니다.", "2명인 가족이 가장 적습니다.", "4명 이상인 가족이 절반입니다." ], answer: 1, explanation: "3명인 가족이 40%로 가장 많습니다." },
        { id: 9, title: "9. 다음은 식당에서 가장 많이 주문한 음식입니다. 설명으로 맞는 것은 무엇입니까?", topic: "음식 주문 (Ordering Food)", chartType: "bar", unit: "%", data: { labels: ['비빔밥', '김치찌개', '불고기', '냉면'], values: [30, 25, 35, 10] }, options: [ "냉면이 가장 많이 팔렸습니다.", "김치찌개가 불고기보다 많습니다.", "불고기가 가장 많이 팔렸습니다.", "비빔밥은 50% 이상입니다." ], answer: 2, explanation: "불고기가 35%로 가장 많이 팔렸습니다." },
        { id: 10, title: "10. 다음은 한 달 동안 물건을 구입하는 데 쓴 돈입니다. 설명으로 맞는 것은 무엇입니까?", topic: "물건 구입 (Shopping / Expenses)", chartType: "bar", unit: "%", data: { labels: ['식료품', '옷', '신발', '생활용품'], values: [35, 20, 10, 25] }, options: [ "신발에 가장 많이 썼습니다.", "식료품에 가장 많이 썼습니다.", "옷과 생활용품은 합해서 30% 입니다.", "생활용품이 신발보다 적습니다." ], answer: 1, explanation: "식료품(35%)에 가장 돈을 많이 썼습니다." },
        { id: 11, title: "11. 다음은 집안일을 하는 시간입니다. 설명으로 맞는 것은 무엇입니까?", topic: "집안일 (Housework)", chartType: "bar", unit: "시간", data: { labels: ['청소', '빨래', '설거지', '요리'], values: [2, 1, 1, 2] }, options: [ "빨래가 가장 깁니다.", "청소와 요리 시간은 같습니다.", "설거지는 3시간입니다.", "청소가 요리보다 짧습니다." ], answer: 1, explanation: "청소(2시간)와 요리(2시간) 시간은 같습니다." },
        { id: 12, title: "12. 다음은 출퇴근할 때 이용하는 교통수단입니다. 설명으로 맞는 것은 무엇입니까?", topic: "대중교통 (Transportation)", chartType: "pie", unit: "%", data: { labels: ['지하철', '버스', '도보', '택시'], values: [45, 30, 15, 10] }, options: [ "택시를 이용하는 사람이 가장 많습니다.", "도보가 버스보다 많습니다.", "지하철을 이용하는 사람이 가장 많습니다.", "버스와 택시가 절반입니다." ], answer: 2, explanation: "지하철 이용자가 45%로 가장 많습니다." },
        { id: 13, title: "13. 다음은 주말에 하는 활동을 조사한 결과입니다. 설명으로 맞는 것은 무엇입니까?", topic: "주말 활동 (Weekend Activities)", chartType: "bar", unit: "%", data: { labels: ['영화 보기', '운동', '쇼핑', '친구 만나기'], values: [25, 20, 30, 25] }, options: [ "운동이 가장 많습니다.", "쇼핑이 가장 많습니다.", "영화 보기가 가장 적습니다.", "친구 만나기가 절반입니다." ], answer: 1, explanation: "쇼핑이 30%로 가장 많습니다." },
        { id: 14, title: "14. 다음은 목적지까지 걸리는 시간을 나타낸 것입니다. 설명으로 맞는 것은 무엇입니까?", topic: "길 찾기 (Directions / Time)", chartType: "bar", unit: "분", data: { labels: ['은행', '병원', '시장', '우체국'], values: [10, 15, 20, 5] }, options: [ "우체국이 가장 멉니다.", "시장이 병원보다 가깝습니다.", "시장이 가장 오래 걸립니다.", "은행까지 20분이 걸립니다." ], answer: 2, explanation: "시장이 20분으로 가장 오래 걸립니다." },
        { id: 15, title: "15. 다음은 계절별로 많이 입는 옷의 종류입니다. 설명으로 맞는 것은 무엇입니까?", topic: "옷차림 (Clothing)", chartType: "bar", unit: "%", data: { labels: ['봄', '여름', '가을', '겨울'], values: [25, 40, 20, 15] }, options: [ "여름이 가장 많습니다.", "겨울이 봄보다 많습니다.", "가을이 여름보다 많습니다.", "봄은 10% 입니다." ], answer: 0, explanation: "여름 옷차림 비율이 40%로 가장 많습니다." },
        { id: 16, title: "16. 다음은 집을 구할 때 중요하게 생각하는 조건입니다. 설명으로 맞는 것은 무엇입니까?", topic: "집 구하기 (House Hunting)", chartType: "pie", unit: "%", data: { labels: ['월세', '위치', '교통', '크기'], values: [30, 25, 25, 20] }, options: [ "크기가 가장 중요합니다.", "월세가 가장 중요합니다.", "위치가 교통보다 많습니다.", "교통이 월세보다 많습니다." ], answer: 1, explanation: "월세가 30%로 가장 중요한 조건입니다." },
        { id: 17, title: "17. 다음은 휴가 때 하고 싶은 활동을 조사한 결과입니다. 설명으로 맞는 것은 무엇입니까?", topic: "휴가 (Vacation)", chartType: "bar", unit: "%", data: { labels: ['고향 방문', '여행', '휴식', '친구 만나기'], values: [35, 30, 20, 15] }, options: [ "친구 만나기가 가장 많습니다.", "휴식이 여행보다 많습니다.", "고향 방문이 가장 많습니다.", "여행과 친구 만나기의 합은 50% 이상입니다." ], answer: 2, explanation: "고향 방문이 35%로 가장 많습니다." },
        { id: 18, title: "18. 다음은 외국인 근로자들이 좋아하는 취미입니다. 설명으로 맞는 것은 무엇입니까?", topic: "취미 (Hobbies)", chartType: "bar", unit: "%", data: { labels: ['운동', '영화', '음악', '독서'], values: [30, 25, 25, 20] }, options: [ "운동이 가장 많습니다.", "음악이 가장 많습니다.", "독서가 영화보다 적습니다.", "영화는 10% 입니다." ], answer: 0, explanation: "운동이 30%로 가장 인기 있습니다." },
        { id: 19, title: "19. 다음은 한국 음식의 재료를 구입하는 비율입니다. 설명으로 맞는 것은 무엇입니까?", topic: "요리 (Cooking Ingredients)", chartType: "bar", unit: "%", data: { labels: ['채소', '고기', '쌀', '양념'], values: [30, 25, 25, 20] }, options: [ "양념이 가장 많습니다.", "채소가 가장 많습니다.", "고기와 쌀의 비율은 다릅니다.", "쌀이 채소보다 많습니다." ], answer: 1, explanation: "채소가 30%로 가장 구매 비율이 높습니다." },
        { id: 20, title: "20. 다음은 스마트폰을 사용하는 목적입니다. 설명으로 맞는 것은 무엇입니까?", topic: "인터넷과 스마트폰 (Smartphone Usage)", chartType: "pie", unit: "%", data: { labels: ['메신저', '동영상', '정보 검색', '쇼핑'], values: [40, 25, 20, 15] }, options: [ "쇼핑이 가장 많습니다.", "메신저가 가장 많습니다.", "동영상이 메신저보다 많습니다.", "정보 검색은 5% 입니다." ], answer: 1, explanation: "메신저 사용이 40%로 가장 많습니다." }
    ]
};
