window.allExams = window.allExams || {};
window.allExams["exam7"] = {
    id: "exam7",
    title: "Korean Vocabulary: Noun Synonyms & Antonyms (150 Items)",
    description: "Advanced 150-item test covering noun synonyms and antonyms based on official EPS-TOPIK / study lists.",
    questions: [
        { q: "What is the synonym of 달 (month)?", options: ["월", "현금", "야간", "가격"], answer: 0 },
        { q: "What is the antonym of 달 (month)?", options: ["낮", "위", "공용", "내부"], answer: 0 },
        { q: "What is the synonym of 돈 (money)?", options: ["현금", "달", "값", "중간"], answer: 0 },
        { q: "What is the antonym of 돈 (money)?", options: ["주간", "아래", "외부", "무료"], answer: 0 },
        { q: "What is the synonym of 밤 (night)?", options: ["야간", "달", "돈", "가격"], answer: 0 },
        { q: "What is the antonym of 밤 (night)?", options: ["낮", "위", "공용", "안"], answer: 0 },
        { q: "What is the synonym of 가격 (price)?", options: ["값", "돈", "달", "밤"], answer: 0 },
        { q: "What is the antonym of 가격 (price)?", options: ["주간", "아래", "외부", "무료"], answer: 0 },
        { q: "What is the synonym of 아래 (under, below)?", options: ["밑", "위", "중간", "밖"], answer: 0 },
        { q: "What is the antonym of 아래 (under, below)?", options: ["위", "낮", "공용", "내부"], answer: 0 },
        { q: "What is the synonym of 중간 (center, middle)?", options: ["가운데", "밖", "구역", "온도"], answer: 0 },
        { q: "What is the antonym of 중간 (center, middle)?", options: ["건너편", "위", "아래", "야간"], answer: 0 },
        { q: "What is the synonym of 맞은편 (opposite side)?", options: ["건너편", "가운데", "구역", "도구"], answer: 0 },
        { q: "What is the synonym of 외부 (outside)?", options: ["바깥", "안", "위", "아래"], answer: 0 },
        { q: "What is the antonym of 외부 (outside)?", options: ["내부", "위", "낮", "공용"], answer: 0 },
        { q: "What is the synonym of 지역 (area, district)?", options: ["구역", "온도", "도구", "옷차림"], answer: 0 },
        { q: "What is the synonym of 기온 (temperature)?", options: ["온도", "지역", "도구", "임금"], answer: 0 },
        { q: "What is the synonym of 도구 (tool)?", options: ["공구", "지역", "온도", "직원"], answer: 0 },
        { q: "What is the synonym of 복장 (clothes, dress)?", options: ["옷차림", "임금", "조건", "허가"], answer: 0 },
        { q: "What is the synonym of 급여 (pay, salary)?", options: ["임금", "복장", "사원", "업무"], answer: 0 },
        { q: "What is the synonym of 사원 (employee, staff)?", options: ["직원", "급여", "자격", "요리"], answer: 0 },
        { q: "What is the synonym of 자격 (qualification)?", options: ["조건", "사원", "급여", "복장"], answer: 0 },
        { q: "What is the synonym of 업무 (work, task)?", options: ["일", "허가", "비자", "사료"], answer: 0 },
        { q: "What is the synonym of 허가 (permission)?", options: ["사증", "업무", "자격", "요리"], answer: 0 },
        { q: "What is the synonym of 비자 (visa)?", options: ["사증", "허가", "요리", "먹이"], answer: 0 },
        { q: "What is the synonym of 요리 (cook)?", options: ["사료", "비자", "허가", "업무"], answer: 0 },
        { q: "What is the synonym of 먹이 (feed)?", options: ["사료", "요리", "비자", "허가"], answer: 0 },
        { q: "What is the synonym of 노동 (labor)?", options: ["근로", "이유", "기준", "소재"], answer: 0 },
        { q: "What is the antonym of 노동 (labor)?", options: ["불결", "결석", "퇴사", "거짓"], answer: 0 },
        { q: "What is the synonym of 사유 (reason, cause)?", options: ["이유", "노동", "기준", "위생"], answer: 0 },
        { q: "What is the synonym of 표준 (standard)?", options: ["기준", "사유", "소재", "해변"], answer: 0 },
        { q: "What is the synonym of 주소 (address)?", options: ["소재지", "표준", "위생", "규칙"], answer: 0 },
        { q: "What is the synonym of 위생 (sanitation, cleanliness)?", options: ["청결", "주소", "기준", "가입"], answer: 0 },
        { q: "What is the antonym of 위생 (sanitation)?", options: ["불결", "청결", "출석", "취업"], answer: 0 },
        { q: "What is the synonym of 바닷가 (beach)?", options: ["해변", "위생", "주소", "규칙"], answer: 0 },
        { q: "What is the synonym of 규칙 (rule)?", options: ["수칙", "바닷가", "청결", "가입"], answer: 0 },
        { q: "What is the synonym of 출석 (attendance)?", options: ["참석", "결석", "탈퇴", "종강"], answer: 0 },
        { q: "What is the antonym of 출석 (attendance)?", options: ["결석", "참석", "가입", "개강"], answer: 0 },
        { q: "What is the synonym of 가입 (join)?", options: ["입사", "탈퇴", "퇴사", "폐업"], answer: 0 },
        { q: "What is the antonym of 가입 (join)?", options: ["탈퇴", "가입", "출석", "종강"], answer: 0 },
        { q: "What is the synonym of 입사 (joining a company)?", options: ["취업", "퇴사", "결석", "거짓"], answer: 0 },
        { q: "What is the antonym of 입사 (joining a company)?", options: ["퇴사", "입사", "개강", "수입"], answer: 0 },
        { q: "What is the synonym of 진실 (truth)?", options: ["거짓", "개강", "종강", "선불"], answer: 0 },
        { q: "What is the antonym of 진실 (truth)?", options: ["거짓", "진실", "최고", "유료"], answer: 0 },
        { q: "What is the synonym of 개업 (open)?", options: ["폐업", "개강", "종강", "실내"], answer: 0 },
        { q: "What is the antonym of 개업 (open)?", options: ["폐업", "개업", "수입", "무료"], answer: 0 },
        { q: "What is the synonym of 개강 (opening of course)?", options: ["종강", "개업", "폐업", "진실"], answer: 0 },
        { q: "What is the antonym of 개강 (opening of course)?", options: ["종강", "개강", "출석", "가입"], answer: 0 },
        { q: "What is the synonym of 선불 (prepaid)?", options: ["후불", "수입", "최고", "실외"], answer: 0 },
        { q: "What is the antonym of 선불 (prepaid)?", options: ["후불", "선불", "유료", "합법"], answer: 0 },
        { q: "What is the synonym of 수출 (export)?", options: ["수입", "선불", "최고", "실외"], answer: 0 },
        { q: "What is the antonym of 수출 (export)?", options: ["수입", "수출", "유료", "불법"], answer: 0 },
        { q: "What is the synonym of 초보 (novice)?", options: ["경력자", "최고", "최저", "실내"], answer: 0 },
        { q: "What is the antonym of 초보 (novice)?", options: ["경력자", "초보", "선불", "후불"], answer: 0 },
        { q: "What is the synonym of 최저 (minimum)?", options: ["최고", "초보", "경력자", "실외"], answer: 0 },
        { q: "What is the antonym of 최저 (minimum)?", options: ["최고", "최저", "무료", "유료"], answer: 0 },
        { q: "What is the synonym of 실내 (interior)?", options: ["실외", "최고", "최저", "초보"], answer: 0 },
        { q: "What is the antonym of 실내 (interior)?", options: ["실외", "실내", "합법", "불법"], answer: 0 },
        { q: "What is the synonym of 무료 (free of charge)?", options: ["유료", "선불", "후불", "수출"], answer: 0 },
        { q: "What is the antonym of 무료 (free of charge)?", options: ["유료", "무료", "최고", "최저"], answer: 0 },
        { q: "What is the synonym of 합법 (legality)?", options: ["불법", "유료", "실내", "초보"], answer: 0 },
        { q: "What is the antonym of 합법 (legality)?", options: ["불법", "합법", "선불", "후불"], answer: 0 },
        { q: "Synonym check: What word means the same as '달'?", options: ["월", "밤", "돈", "값"], answer: 0 },
        { q: "Antonym check: What is the opposite of '달'?", options: ["낮", "밤", "돈", "값"], answer: 0 },
        { q: "Synonym check: What word means the same as '돈'?", options: ["현금", "달", "밤", "가격"], answer: 0 },
        { q: "Antonym check: What is the opposite of '돈'?", options: ["주간", "야간", "값", "밑"], answer: 0 },
        { q: "Synonym check: What word means the same as '밤'?", options: ["야간", "낮", "월", "현금"], answer: 0 },
        { q: "Antonym check: What is the opposite of '밤'?", options: ["주간", "야간", "달", "돈"], answer: 0 },
        { q: "Synonym check: What word means the same as '가격'?", options: ["값", "돈", "달", "밤"], answer: 0 },
        { q: "Antonym check: What is the opposite of '가격'?", options: ["주간", "야간", "낮", "위"], answer: 0 },
        { q: "Synonym check: What word means the same as '아래'?", options: ["밑", "위", "중간", "밖"], answer: 0 },
        { q: "Antonym check: What is the opposite of '아래'?", options: ["위", "밑", "중간", "밖"], answer: 0 },
        { q: "Synonym check: What word means the same as '중간'?", options: ["가운데", "밖", "위", "아래"], answer: 0 },
        { q: "Antonym check: What is the opposite of '중간'?", options: ["건너편", "가운데", "위", "아래"], answer: 0 },
        { q: "Synonym check: What word means the same as '맞은편'?", options: ["건너편", "가운데", "위", "아래"], answer: 0 },
        { q: "Synonym check: What word means the same as '외부'?", options: ["바깥", "안", "중간", "밑"], answer: 0 },
        { q: "Antonym check: What is the opposite of '외부'?", options: ["내부", "바깥", "중간", "밑"], answer: 0 },
        { q: "Synonym check: What word means the same as '지역'?", options: ["구역", "온도", "도구", "옷차림"], answer: 0 },
        { q: "Synonym check: What word means the same as '기온'?", options: ["온도", "지역", "도구", "임금"], answer: 0 },
        { q: "Synonym check: What word means the same as '도구'?", options: ["공구", "지역", "온도", "직원"], answer: 0 },
        { q: "Synonym check: What word means the same as '복장'?", options: ["옷차림", "임금", "조건", "허가"], answer: 0 },
        { q: "Synonym check: What word means the same as '급여'?", options: ["월급", "복장", "사원", "업무"], answer: 0 },
        { q: "Synonym check: What word means the same as '사원'?", options: ["직원", "급여", "자격", "요리"], answer: 0 },
        { q: "Synonym check: What word means the same as '자격'?", options: ["조건", "사원", "급여", "복장"], answer: 0 },
        { q: "Synonym check: What word means the same as '업무'?", options: ["일", "허가", "비자", "사료"], answer: 0 },
        { q: "Synonym check: What word means the same as '허가'?", options: ["사증", "업무", "자격", "요리"], answer: 0 },
        { q: "Synonym check: What word means the same as '비자'?", options: ["사증", "허가", "요리", "먹이"], answer: 0 },
        { q: "Synonym check: What word means the same as '요리'?", options: ["사료", "비자", "허가", "업무"], answer: 0 },
        { q: "Synonym check: What word means the same as '먹이'?", options: ["사료", "요리", "비자", "허가"], answer: 0 },
        { q: "Synonym check: What word means the same as '노동'?", options: ["근로", "이유", "기준", "위생"], answer: 0 },
        { q: "Antonym check: What is the opposite of '노동'?", options: ["휴식", "근로", "이유", "기준"], answer: 0 },
        { q: "Synonym check: What word means the same as '사유'?", options: ["이유", "노동", "기준", "위생"], answer: 0 },
        { q: "Synonym check: What word means the same as '표준'?", options: ["기준", "사유", "소재", "해변"], answer: 0 },
        { q: "Synonym check: What word means the same as '주소'?", options: ["소재지", "표준", "위생", "규칙"], answer: 0 },
        { q: "Synonym check: What word means the same as '위생'?", options: ["청결", "주소", "기준", "가입"], answer: 0 },
        { q: "Antonym check: What is the opposite of '위생'?", options: ["불결", "청결", "기준", "주소"], answer: 0 },
        { q: "Synonym check: What word means the same as '바닷가'?", options: ["해변", "위생", "주소", "규칙"], answer: 0 },
        { q: "Synonym check: What word means the same as '규칙'?", options: ["수칙", "바닷가", "청결", "가입"], answer: 0 },
        { q: "Synonym check: What word means the same as '출석'?", options: ["참석", "결석", "탈퇴", "종강"], answer: 0 },
        { q: "Antonym check: What is the opposite of '출석'?", options: ["결석", "참석", "가입", "탈퇴"], answer: 0 },
        { q: "Synonym check: What word means the same as '가입'?", options: ["입사", "탈퇴", "퇴사", "폐업"], answer: 0 },
        { q: "Antonym check: What is the opposite of '가입'?", options: ["탈퇴", "입사", "퇴사", "폐업"], answer: 0 },
        { q: "Synonym check: What word means the same as '입사'?", options: ["취업", "퇴사", "결석", "거짓"], answer: 0 },
        { q: "Antonym check: What is the opposite of '입사'?", options: ["퇴사", "취업", "결석", "거짓"], answer: 0 },
        { q: "Synonym check: What word means the same as '진실'?", options: ["참", "거짓", "개강", "종강"], answer: 0 },
        { q: "Antonym check: What is the opposite of '진실'?", options: ["거짓", "참", "개강", "종강"], answer: 0 },
        { q: "Synonym check: What word means the same as '개업'?", options: ["시작", "폐업", "개강", "종강"], answer: 0 },
        { q: "Antonym check: What is the opposite of '개업'?", options: ["폐업", "시작", "개강", "종강"], answer: 0 },
        { q: "Synonym check: What word means the same as '개강'?", options: ["시작", "종강", "개업", "폐업"], answer: 0 },
        { q: "Antonym check: What is the opposite of '개강'?", options: ["종강", "시작", "개업", "폐업"], answer: 0 },
        { q: "Synonym check: What word means the same as '선불'?", options: ["미리", "후불", "수입", "수출"], answer: 0 },
        { q: "Antonym check: What is the opposite of '선불'?", options: ["후불", "미리", "수입", "수출"], answer: 0 },
        { q: "Synonym check: What word means the same as '수출'?", options: ["판매", "수입", "선불", "후불"], answer: 0 },
        { q: "Antonym check: What is the opposite of '수출'?", options: ["수입", "판매", "선불", "후불"], answer: 0 },
        { q: "Synonym check: What word means the same as '초보'?", options: ["처음", "경력자", "최고", "최저"], answer: 0 },
        { q: "Antonym check: What is the opposite of '초보'?", options: ["경력자", "처음", "최고", "최저"], answer: 0 },
        { q: "Synonym check: What word means the same as '최저'?", options: ["가장 낮음", "최고", "초보", "경력자"], answer: 0 },
        { q: "Antonym check: What is the opposite of '최저'?", options: ["최고", "가장 낮음", "초보", "경력자"], answer: 0 },
        { q: "Synonym check: What word means the same as '실내'?", options: ["안", "실외", "무료", "유료"], answer: 0 },
        { q: "Antonym check: What is the opposite of '실내'?", options: ["실외", "안", "무료", "유료"], answer: 0 },
        { q: "Synonym check: What word means the same as '무료'?", options: ["공짜", "유료", "합법", "불법"], answer: 0 },
        { q: "Antonym check: What is the opposite of '무료'?", options: ["유료", "공짜", "합법", "불법"], answer: 0 },
        { q: "Synonym check: What word means the same as '합법'?", options: ["정식", "불법", "무료", "유료"], answer: 0 },
        { q: "Antonym check: What is the opposite of '합법'?", options: ["불법", "정식", "무료", "유료"], answer: 0 },
        { q: "What is the synonym of '노동'?", options: ["근로", "휴식", "취업", "퇴사"], answer: 0 },
        { q: "What is the antonym of '노동'?", options: ["휴식", "근로", "취업", "퇴사"], answer: 0 },
        { q: "What is the synonym of '사유'?", options: ["원인", "결과", "목적", "시작"], answer: 0 },
        { q: "What is the synonym of '표준'?", options: ["기준", "예외", "변화", "다름"], answer: 0 },
        { q: "What is the synonym of '위생'?", options: ["청결", "불결", "오염", "더러움"], answer: 0 },
        { q: "What is the synonym of '바닷가'?", options: ["해변", "산", "강", "들판"], answer: 0 },
        { q: "What is the synonym of '규칙'?", options: ["규율", "위반", "자유", "방해"], answer: 0 },
        { q: "What is the synonym of '진실'?", options: ["참", "거짓", "농담", "비밀"], answer: 0 },
        { q: "What is the synonym of '초보'?", options: ["초급자", "전문가", "베테랑", "달인"], answer: 0 },
        { q: "What is the synonym of '실내'?", options: ["안", "밖", "외부", "야외"], answer: 0 },
        { q: "What is the synonym of '합법'?", options: ["정식", "불법", "위법", "탈법"], answer: 0 },
        { q: "What is the antonym of '합법'?", options: ["불법", "정식", "공식", "허가"], answer: 0 },
        { q: "What is the synonym of '무료'?", options: ["공짜", "유료", "비쌈", "값어치"], answer: 0 },
        { q: "What is the antonym of '무료'?", options: ["유료", "공짜", "서비스", "나눔"], answer: 0 },
        { q: "What is the synonym of '수출'?", options: ["내보내기", "수입", "들여오기", "반입"], answer: 0 },
        { q: "What is the antonym of '수출'?", options: ["수입", "내보내기", "발송", "선적"], answer: 0 }
    ]
};
