window.allExams = window.allExams || {};
window.allExams["exam1"] = {
    id: "exam1",
    title: "Picture Vocabs Test 1",
    subtitle: "Vocabulary Practice Test 1 (Questions 1–100)",
    badge: "어휘 (Vocabulary)",
    description: "영어 단어를 보고 알맞은 한국어 단어를 찾는 어휘 실전 100문제",
    questions: [
        { id: 1, type: "text", title: "1. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "Sun", options: ["태양", "달", "구름", "바람"], answer: 0, explanation: "'Sun'의 한국어 뜻은 '태양'입니다." },
        { id: 2, type: "text", title: "2. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "Moon", options: ["태양", "달", "별", "안개"], answer: 1, explanation: "'Moon'의 한국어 뜻은 '달'입니다." },
        { id: 3, type: "text", title: "3. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "Star", options: ["구름", "비", "별", "눈"], answer: 2, explanation: "'Star'의 한국어 뜻은 '별'입니다." },
        { id: 4, type: "text", title: "4. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "Cloud", options: ["안개", "바람", "산", "구름"], answer: 3, explanation: "'Cloud'의 한국어 뜻은 '구름'입니다." },
        { id: 5, type: "text", title: "5. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "Rain", options: ["눈", "비", "강", "바다"], answer: 1, explanation: "'Rain'의 한국어 뜻은 '비'입니다." },
        { id: 6, type: "text", title: "6. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "Snow", options: ["비", "바람", "호수", "눈"], answer: 3, explanation: "'Snow'의 한국어 뜻은 '눈'입니다." },
        { id: 7, type: "text", title: "7. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "Wind", options: ["태양", "바람", "안개", "계곡"], answer: 1, explanation: "'Wind'의 한국어 뜻은 '바람'입니다." },
        { id: 8, type: "text", title: "8. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "Fog", options: ["구름", "안개", "섬", "숲"], answer: 1, explanation: "'Fog'의 한국어 뜻은 '안개'입니다." },
        { id: 9, type: "text", title: "9. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "Mountain", options: ["강", "바다", "산", "숲"], answer: 2, explanation: "'Mountain'의 한국어 뜻은 '산'입니다." },
        { id: 10, type: "text", title: "10. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "River", options: ["바다", "호수", "강", "계곡"], answer: 2, explanation: "'River'의 한국어 뜻은 '강'입니다." },
        { id: 11, type: "text", title: "11. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "Sea", options: ["산", "섬", "나무", "바다"], answer: 3, explanation: "'Sea'의 한국어 뜻은 '바다'입니다." },
        { id: 12, type: "text", title: "12. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "Lake", options: ["강", "호수", "계곡", "풀"], answer: 1, explanation: "'Lake'의 한국어 뜻은 '호수'입니다." },
        { id: 13, type: "text", title: "13. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "Valley", options: ["산", "계곡", "섬", "꽃"], answer: 1, explanation: "'Valley'의 한국어 뜻은 '계곡'입니다." },
        { id: 14, type: "text", title: "14. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "Island", options: ["바다", "숲", "섬", "나무"], answer: 2, explanation: "'Island'의 한국어 뜻은 '섬'입니다." },
        { id: 15, type: "text", title: "15. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "Forest", options: ["풀", "꽃", "달", "숲"], answer: 3, explanation: "'Forest'의 한국어 뜻은 '숲'입니다." },
        { id: 16, type: "text", title: "16. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "Tree", options: ["풀", "나무", "꽃", "비"], answer: 1, explanation: "'Tree'의 한국어 뜻은 '나무'입니다." },
        { id: 17, type: "text", title: "17. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "Grass", options: ["나무", "산", "풀", "강"], answer: 2, explanation: "'Grass'의 한국어 뜻은 '풀'입니다." },
        { id: 18, type: "text", title: "18. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "자연과 환경 (Nature)", word: "Flower", options: ["사과", "포도", "나무", "꽃"], answer: 3, explanation: "'Flower'의 한국어 뜻은 '꽃'입니다." },
        { id: 19, type: "text", title: "19. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Cooked Rice", options: ["국", "밥", "반찬", "김치"], answer: 1, explanation: "'Cooked Rice'의 한국어 뜻은 '밥'입니다." },
        { id: 20, type: "text", title: "20. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Soup", options: ["밥", "우유", "국", "물"], answer: 2, explanation: "'Soup'의 한국어 뜻은 '국'입니다." },
        { id: 21, type: "text", title: "21. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Side Dishes", options: ["라면", "국수", "갈비", "반찬"], answer: 3, explanation: "'Side Dishes'의 한국어 뜻은 '반찬'입니다." },
        { id: 22, type: "text", title: "22. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Kimchi", options: ["피클", "김치", "단무지", "사과"], answer: 1, explanation: "'Kimchi'의 한국어 명칭은 '김치'입니다." },
        { id: 23, type: "text", title: "23. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Soybean Paste Soup", options: ["미역국", "불고기", "삼겹살", "된장국"], answer: 3, explanation: "'Soybean Paste Soup'의 한국어 뜻은 '된장국'입니다." },
        { id: 24, type: "text", title: "24. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Seaweed Soup", options: ["김치찌개", "미역국", "순두부찌개", "우동"], answer: 1, explanation: "'Seaweed Soup'의 한국어 뜻은 '미역국'입니다." },
        { id: 25, type: "text", title: "25. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Kimchi Stew", options: ["된장국", "냉면", "김치찌개", "차"], answer: 2, explanation: "'Kimchi Stew'의 한국어 뜻은 '김치찌개'입니다." },
        { id: 26, type: "text", title: "26. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Soft Tofu Stew", options: ["순두부찌개", "불고기", "닭고기", "깍두기"], answer: 0, explanation: "'Soft Tofu Stew'의 한국어 뜻은 '순두부찌개'입니다." },
        { id: 27, type: "text", title: "27. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Bulgogi (Grilled Marinated Beef)", options: ["삼겹살", "불고기", "갈비", "닭고기"], answer: 1, explanation: "'Bulgogi'의 한국어 명칭은 '불고기'입니다." },
        { id: 28, type: "text", title: "28. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Pork Belly", options: ["갈비", "닭고기", "삼겹살", "라면"], answer: 2, explanation: "'Pork Belly'의 한국어 뜻은 '삼겹살'입니다." },
        { id: 29, type: "text", title: "29. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Ribs (Galbi)", options: ["불고기", "삼겹살", "피클", "갈비"], answer: 3, explanation: "'Ribs'의 한국어 명칭은 '갈비'입니다." },
        { id: 30, type: "text", title: "30. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Chicken", options: ["갈비", "닭고기", "김치", "우유"], answer: 1, explanation: "'Chicken'의 한국어 뜻은 '닭고기'입니다." },
        { id: 31, type: "text", title: "31. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Cubed Radish Kimchi", options: ["단무지", "피클", "깍두기", "사과"], answer: 2, explanation: "'Cubed Radish Kimchi'의 한국어 명칭은 '깍두기'입니다." },
        { id: 32, type: "text", title: "32. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Pickled Radish", options: ["피클", "단무지", "귤", "배"], answer: 1, explanation: "'Pickled Radish'의 한국어 뜻은 '단무지'입니다." },
        { id: 33, type: "text", title: "33. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Pickles", options: ["단무지", "바나나", "수박", "피클"], answer: 3, explanation: "'Pickles'의 한국어 뜻은 '피클'입니다." },
        { id: 34, type: "text", title: "34. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Milk", options: ["주스", "우유", "물", "탄산음료"], answer: 1, explanation: "'Milk'의 한국어 뜻은 '우유'입니다." },
        { id: 35, type: "text", title: "35. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Juice", options: ["커피", "주스", "차", "우유"], answer: 1, explanation: "'Juice'의 한국어 뜻은 '주스'입니다." },
        { id: 36, type: "text", title: "36. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Coffee", options: ["차", "물", "탄산음료", "커피"], answer: 3, explanation: "'Coffee'의 한국어 뜻은 '커피'입니다." },
        { id: 37, type: "text", title: "37. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Water", options: ["우유", "물", "주스", "차"], answer: 1, explanation: "'Water'의 한국어 뜻은 '물'입니다." },
        { id: 38, type: "text", title: "38. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Tea", options: ["커피", "차", "주스", "우동"], answer: 1, explanation: "'Tea'의 한국어 뜻은 '차'입니다." },
        { id: 39, type: "text", title: "39. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Apple", options: ["배", "귤", "포도", "사과"], answer: 3, explanation: "'Apple'의 한국어 뜻은 '사과'입니다." },
        { id: 40, type: "text", title: "40. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Pear", options: ["사과", "배", "수박", "바나나"], answer: 1, explanation: "'Pear'의 한국어 뜻은 '배'입니다." },
        { id: 41, type: "text", title: "41. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Banana", options: ["귤", "포도", "바나나", "사과"], answer: 2, explanation: "'Banana'의 한국어 뜻은 '바나나'입니다." },
        { id: 42, type: "text", title: "42. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Tangerine", options: ["사과", "배", "포도", "귤"], answer: 3, explanation: "'Tangerine'의 한국어 뜻은 '귤'입니다." },
        { id: 43, type: "text", title: "43. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Grapes", options: ["포도", "수박", "사과", "바나나"], answer: 0, explanation: "'Grapes'의 한국어 뜻은 '포도'입니다." },
        { id: 44, type: "text", title: "44. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Watermelon", options: ["귤", "배", "수박", "포도"], answer: 2, explanation: "'Watermelon'의 한국어 뜻은 '수박'입니다." },
        { id: 45, type: "text", title: "45. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Ramen (Instant Noodles)", options: ["국수", "우동", "라면", "냉면"], answer: 2, explanation: "'Ramen'의 한국어 뜻은 '라면'입니다." },
        { id: 46, type: "text", title: "46. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Noodles", options: ["라면", "국수", "우동", "탄산음료"], answer: 1, explanation: "'Noodles'의 한국어 뜻은 '국수'입니다." },
        { id: 47, type: "text", title: "47. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Udon", options: ["냉면", "라면", "우동", "국수"], answer: 2, explanation: "'Udon'의 한국어 뜻은 '우동'입니다." },
        { id: 48, type: "text", title: "48. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Cold Noodles (Naengmyeon)", options: ["우동", "라면", "국수", "냉면"], answer: 3, explanation: "'Cold Noodles'의 한국어 뜻은 '냉면'입니다." },
        { id: 49, type: "text", title: "49. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "음식과 음료 (Food & Drinks)", word: "Soda / Carbonated Drink", options: ["우유", "주스", "탄산음료", "물"], answer: 2, explanation: "'Soda'의 한국어 뜻은 '탄산음료'입니다." },
        { id: 50, type: "text", title: "50. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Bag", options: ["지갑", "모자", "우산", "가방"], answer: 3, explanation: "'Bag'의 한국어 뜻은 '가방'입니다." },
        { id: 51, type: "text", title: "51. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Wallet", options: ["가방", "지갑", "거울", "시계"], answer: 1, explanation: "'Wallet'의 한국어 뜻은 '지갑'입니다." },
        { id: 52, type: "text", title: "52. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Bag Strap", options: ["가방걸이", "우산", "가방끈", "우비"], answer: 2, explanation: "'Bag Strap'의 한국어 뜻은 '가방끈'입니다." },
        { id: 53, type: "text", title: "53. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Bag Hanger", options: ["가방끈", "가방걸이", "선반", "의자"], answer: 1, explanation: "'Bag Hanger'의 한국어 뜻은 '가방걸이'입니다." },
        { id: 54, type: "text", title: "54. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Umbrella", options: ["양산", "우비", "우산", "모자"], answer: 2, explanation: "'Umbrella'의 한국어 뜻은 '우산'입니다." },
        { id: 55, type: "text", title: "55. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Raincoat", options: ["우산", "우비", "양산", "이불"], answer: 1, explanation: "'Raincoat'의 한국어 뜻은 '우비'입니다." },
        { id: 56, type: "text", title: "56. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Hat / Cap", options: ["우산", "가방", "모자", "베개"], answer: 2, explanation: "'Hat / Cap'의 한국어 뜻은 '모자'입니다." },
        { id: 57, type: "text", title: "57. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Parasol", options: ["우산", "모자", "창문", "양산"], answer: 3, explanation: "'Parasol'의 한국어 뜻은 '양산'입니다." },
        { id: 58, type: "text", title: "58. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Desk", options: ["식탁", "책상", "의자", "선반"], answer: 1, explanation: "'Desk'의 한국어 뜻은 '책상'입니다." },
        { id: 59, type: "text", title: "59. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Dining Table", options: ["책상", "선반", "식탁", "침대"], answer: 2, explanation: "'Dining Table'의 한국어 뜻은 '식탁'입니다." },
        { id: 60, type: "text", title: "60. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Chair", options: ["책상", "의자", "침대", "문"], answer: 1, explanation: "'Chair'의 한국어 뜻은 '의자'입니다." },
        { id: 61, type: "text", title: "61. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Shelf", options: ["책상", "창문", "달력", "선반"], answer: 3, explanation: "'Shelf'의 한국어 뜻은 '선반'입니다." },
        { id: 62, type: "text", title: "62. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Electric Fan", options: ["에어컨", "선풍기", "히터", "공기청정기"], answer: 1, explanation: "'Electric Fan'의 한국어 뜻은 '선풍기'입니다." },
        { id: 63, type: "text", title: "63. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Heater", options: ["선풍기", "에어컨", "세탁기", "히터"], answer: 3, explanation: "'Heater'의 한국어 뜻은 '히터'입니다." },
        { id: 64, type: "text", title: "64. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Air Conditioner", options: ["선풍기", "에어컨", "히터", "냉장고"], answer: 1, explanation: "'Air Conditioner'의 한국어 뜻은 '에어컨'입니다." },
        { id: 65, type: "text", title: "65. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Air Purifier", options: ["에어컨", "공기청정기", "세탁기", "TV"], answer: 1, explanation: "'Air Purifier'의 한국어 뜻은 '공기청정기'입니다." },
        { id: 66, type: "text", title: "66. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Bed", options: ["매트리스", "침대", "이불", "베개"], answer: 1, explanation: "'Bed'의 한국어 뜻은 '침대'입니다." },
        { id: 67, type: "text", title: "67. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Blanket", options: ["베개", "침대", "매트리스", "이불"], answer: 3, explanation: "'Blanket'의 한국어 뜻은 '이불'입니다." },
        { id: 68, type: "text", title: "68. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Pillow", options: ["이불", "베개", "침대", "거울"], answer: 1, explanation: "'Pillow'의 한국어 뜻은 '베개'입니다." },
        { id: 69, type: "text", title: "69. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Mattress", options: ["침대", "베개", "매트리스", "선반"], answer: 2, explanation: "'Mattress'의 한국어 뜻은 '매트리스'입니다." },
        { id: 70, type: "text", title: "70. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Washing Machine", options: ["냉장고", "세탁기", "전자레인지", "TV"], answer: 1, explanation: "'Washing Machine'의 한국어 뜻은 '세탁기'입니다." },
        { id: 71, type: "text", title: "71. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Refrigerator", options: ["세탁기", "전자레인지", "냉장고", "선반"], answer: 2, explanation: "'Refrigerator'의 한국어 뜻은 '냉장고'입니다." },
        { id: 72, type: "text", title: "72. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Microwave Oven", options: ["냉장고", "TV", "전자레인지", "컴퓨터"], answer: 2, explanation: "'Microwave Oven'의 한국어 뜻은 '전자레인지'입니다." },
        { id: 73, type: "text", title: "73. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Television (TV)", options: ["모니터", "컴퓨터", "TV", "창문"], answer: 2, explanation: "'Television'의 한국어 뜻은 'TV'입니다." },
        { id: 74, type: "text", title: "74. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Computer", options: ["TV", "컴퓨터", "프린터", "휴대폰"], answer: 1, explanation: "'Computer'의 한국어 뜻은 '컴퓨터'입니다." },
        { id: 75, type: "text", title: "75. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Monitor", options: ["TV", "거울", "모니터", "창문"], answer: 2, explanation: "'Monitor'의 한국어 뜻은 '모니터'입니다." },
        { id: 76, type: "text", title: "76. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Printer", options: ["컴퓨터", "전화기", "프린터", "세탁기"], answer: 2, explanation: "'Printer'의 한국어 뜻은 '프린터'입니다." },
        { id: 77, type: "text", title: "77. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Telephone", options: ["휴대폰", "전화기", "충전기", "이어폰"], answer: 1, explanation: "'Telephone'의 한국어 뜻은 '전화기'입니다." },
        { id: 78, type: "text", title: "78. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Cell Phone / Mobile Phone", options: ["전화기", "시계", "휴대폰", "거울"], answer: 2, explanation: "'Cell Phone'의 한국어 뜻은 '휴대폰'입니다." },
        { id: 79, type: "text", title: "79. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Charger", options: ["휴대폰", "충전기", "이어폰", "선풍기"], answer: 1, explanation: "'Charger'의 한국어 뜻은 '충전기'입니다." },
        { id: 80, type: "text", title: "80. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Earphones", options: ["충전기", "전화기", "가방", "이어폰"], answer: 3, explanation: "'Earphones'의 한국어 뜻은 '이어폰'입니다." },
        { id: 81, type: "text", title: "81. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Clock / Watch", options: ["달력", "시계", "거울", "창문"], answer: 1, explanation: "'Clock / Watch'의 한국어 뜻은 '시계'입니다." },
        { id: 82, type: "text", title: "82. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Calendar", options: ["시계", "달력", "창문", "선반"], answer: 1, explanation: "'Calendar'의 한국어 뜻은 '달력'입니다." },
        { id: 83, type: "text", title: "83. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Door", options: ["창문", "문", "벽", "계단"], answer: 1, explanation: "'Door'의 한국어 뜻은 '문'입니다." },
        { id: 84, type: "text", title: "84. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Window", options: ["문", "거울", "창문", "벽"], answer: 2, explanation: "'Window'의 한국어 뜻은 '창문'입니다." },
        { id: 85, type: "text", title: "85. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Wall", options: ["문", "벽", "계단", "선반"], answer: 1, explanation: "'Wall'의 한국어 뜻은 '벽'입니다." },
        { id: 86, type: "text", title: "86. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Mirror", options: ["창문", "시계", "거울", "달력"], answer: 2, explanation: "'Mirror'의 한국어 뜻은 '거울'입니다." },
        { id: 87, type: "text", title: "87. 다음 단어를 보고 맞는 한국어 단어를 고르십시오.", topic: "생활 용품 (Daily Items)", word: "Stairs", options: ["벽", "문", "계단", "선반"], answer: 2, explanation: "'Stairs'의 한국어 뜻은 '계단'입니다." },
        { id: 88, type: "text", title: "88. 다음 단어를 보고 맞는 직업을 고르십시오.", topic: "사람과 직업 (People & Jobs)", word: "Doctor", options: ["간호사", "선생님", "의사", "경찰관"], answer: 2, explanation: "'Doctor'의 한국어 뜻은 '의사'입니다." },
        { id: 89, type: "text", title: "89. 다음 단어를 보고 맞는 직업을 고르십시오.", topic: "사람과 직업 (People & Jobs)", word: "Nurse", options: ["의사", "간호사", "선생님", "소방관"], answer: 1, explanation: "'Nurse'의 한국어 뜻은 '간호사'입니다." },
        { id: 90, type: "text", title: "90. 다음 단어를 보고 맞는 직업을 고르십시오.", topic: "사람과 직업 (People & Jobs)", word: "Teacher", options: ["의사", "군인", "선생님", "회사원"], answer: 2, explanation: "'Teacher'의 한국어 뜻은 '선생님'입니다." },
        { id: 91, type: "text", title: "91. 다음 단어를 보고 맞는 직업을 고르십시오.", topic: "사람과 직업 (People & Jobs)", word: "Police Officer", options: ["소방관", "경비원", "경찰관", "군인"], answer: 2, explanation: "'Police Officer'의 한국어 뜻은 '경찰관'입니다." },
        { id: 92, type: "text", title: "92. 다음 단어를 보고 맞는 직업을 고르십시오.", topic: "사람과 직업 (People & Jobs)", word: "Farmer", options: ["어부", "농부", "건설 근로자", "요리사"], answer: 1, explanation: "'Farmer'의 한국어 뜻은 '농부'입니다." },
        { id: 93, type: "text", title: "93. 다음 단어를 보고 맞는 직업을 고르십시오.", topic: "사람과 직업 (People & Jobs)", word: "Construction Worker", options: ["농부", "경비원", "건설 근로자", "운전기사"], answer: 2, explanation: "'Construction Worker'의 한국어 뜻은 '건설 근로자'입니다." },
        { id: 94, type: "text", title: "94. 다음 단어를 보고 맞는 직업을 고르십시오.", topic: "사람과 직업 (People & Jobs)", word: "Firefighter", options: ["경찰관", "소방관", "군인", "어부"], answer: 1, explanation: "'Firefighter'의 한국어 뜻은 '소방관'입니다." },
        { id: 95, type: "text", title: "95. 다음 단어를 보고 맞는 직업을 고르십시오.", topic: "사람과 직업 (People & Jobs)", word: "Cook / Chef", options: ["선생님", "판매원", "요리사", "회사원"], answer: 2, explanation: "'Cook / Chef'의 한국어 뜻은 '요리사'입니다." },
        { id: 96, type: "text", title: "96. 다음 단어를 보고 맞는 직업을 고르십시오.", topic: "사람과 직업 (People & Jobs)", word: "Soldier", options: ["경찰관", "군인", "경비원", "운전기사"], answer: 1, explanation: "'Soldier'의 한국어 뜻은 '군인'입니다." },
        { id: 97, type: "text", title: "97. 다음 단어를 보고 맞는 직업을 고르십시오.", topic: "사람과 직업 (People & Jobs)", word: "Driver", options: ["택배 기사", "버스 기사", "운전기사", "회사원"], answer: 2, explanation: "'Driver'의 한국어 뜻은 '운전기사'입니다." },
        { id: 98, type: "text", title: "98. 다음 단어를 보고 맞는 직업을 고르십시오.", topic: "사람과 직업 (People & Jobs)", word: "Office Worker", options: ["판매원", "회사원", "선생님", "의사"], answer: 1, explanation: "'Office Worker'의 한국어 뜻은 '회사원'입니다." },
        { id: 99, type: "text", title: "99. 다음 단어를 보고 맞는 직업을 고르십시오.", topic: "사람과 직업 (People & Jobs)", word: "Salesperson", options: ["회사원", "택배 기사", "판매원", "요리사"], answer: 2, explanation: "'Salesperson'의 한국어 뜻은 '판매원'입니다." },
        { id: 100, type: "text", title: "100. 다음 단어를 보고 맞는 직업을 고르십시오.", topic: "사람과 직업 (People & Jobs)", word: "Fisherman", options: ["농부", "어부", "건설 근로자", "군인"], answer: 1, explanation: "'Fisherman'의 한국어 뜻은 '어부'입니다." }
    ]
};
