window.allExams = window.allExams || {};
window.allExams["exam8"] = {
    id: "exam8",
    title: "Verb Synonyms & Antonyms",
    subtitle: "Advanced Practice Test",
    badge: "어휘 (Vocabulary)",
    description: "Advanced 150-item test covering action verbs, synonyms, and antonyms.",
    questions: [
        { q: "What is the synonym of 받다 (receive)?", options: ["타다", "주다", "내리다", "잃다"], answer: 0 },
        { q: "What is the antonym of 받다 (receive)?", options: ["주다", "타다", "얻다", "받아들이다"], answer: 0 },
        { q: "What is the synonym of 바꾸다 (change, exchange)?", options: ["환전하다", "지키다", "가르치다", "시작하다"], answer: 0 },
        { q: "What is the antonym of 시작하다 (start)?", options: ["끝내다", "계속하다", "열다", "만들다"], answer: 0 },
        { q: "What is the synonym of 끝내다 (finish)?", options: ["마치다", "시작하다", "열다", "올리다"], answer: 0 },
        { q: "What is the antonym of 팔다 (sell)?", options: ["사다", "주다", "빌리다", "보내다"], answer: 0 },
        { q: "What is the synonym of 팔다 (sell)?", options: ["판매하다", "사다", "구입하다", "얻다"], answer: 0 },
        { q: "What is the synonym of 사다 (buy)?", options: ["구입하다", "팔다", "판매하다", "버리다"], answer: 0 },
        { q: "What is the antonym of 올리다 (raise, rise)?", options: ["내리다", "낮다", "크다", "멀다"], answer: 0 },
        { q: "What is the synonym of 올리다 (raise)?", options: ["상승하다", "내리다", "떨어지다", "줄이다"], answer: 0 },
        { q: "What is the synonym of 뽑다 (pull out)?", options: ["빼내다", "꽂다", "넣다", "닫다"], answer: 0 },
        { q: "What is the antonym of 뽑다 (pull out)?", options: ["꽂다", "빼내다", "뽑기", "당기다"], answer: 0 },
        { q: "What is the synonym of 입금하다 (deposit)?", options: ["돈을 넣다", "출금하다", "찾다", "뽑다"], answer: 0 },
        { q: "What is the antonym of 입금하다 (deposit)?", options: ["출금하다", "넣다", "모으다", "저축하다"], answer: 0 },
        { q: "What is the synonym of 지키다 (keep, observe)?", options: ["따르다", "어기다", "위반하다", "버리다"], answer: 0 },
        { q: "What is the antonym of 지키다 (keep)?", options: ["어기다", "따르다", "준수하다", "지키기"], answer: 0 },
        { q: "What is the synonym of 환영하다 (welcome)?", options: ["맞이하다", "환송하다", "보내다", "떠나다"], answer: 0 },
        { q: "What is the antonym of 환영하다 (welcome)?", options: ["환송하다", "맞이하다", "좋아하다", "반기다"], answer: 0 },
        { q: "What is the synonym of 이다 (transfer)?", options: ["옮기다", "머무다", "체류하다", "멈추다"], answer: 0 },
        { q: "What is the antonym of 이다 (transfer/move)?", options: ["머무다", "옮기다", "이동", "운반"], answer: 0 },
        { q: "What is the synonym of 짓다 (build, construct)?", options: ["설치하다", "부수다", "파괴하다", "해지하다"], answer: 0 },
        { q: "What is the antonym of 짓다 (build)?", options: ["부수다", "설치하다", "만들다", "만족하다"], answer: 0 },
        { q: "What is the synonym of 출근하다 (go to work)?", options: ["퇴근하다", "출발하다", "도착하다", "쉬다"], answer: 0 },
        { q: "What is the antonym of 출근하다 (go to work)?", options: ["퇴근하다", "지각하다", "출근", "근무"], answer: 0 },
        { q: "What is the synonym of 고르다 (choose, select)?", options: ["선택하다", "버리다", "포기하다", "지우다"], answer: 0 },
        { q: "What is the antonym of 고르다 (choose)?", options: ["제외하다", "선택하다", "고름", "뽑다"], answer: 0 },
        { q: "What is the synonym of 버리다 (throw away)?", options: ["폐기하다", "줍다", "간직하다", "모으다"], answer: 0 },
        { q: "What is the antonym of 버리다 (throw away)?", options: ["줍다", "폐기", "버려짐", "청소"], answer: 0 },
        { q: "What is the synonym of 수입하다 (import)?", options: ["들여오다", "수출하다", "내보내다", "팔다"], answer: 0 },
        { q: "What is the antonym of 수입하다 (import)?", options: ["수출하다", "들여오다", "사다", "구입"], answer: 0 },
        { q: "What is the synonym of 증가하다 (increase)?", options: ["늘다", "줄다", "감소하다", "내리다"], answer: 0 },
        { q: "What is the antonym of 증가하다 (increase)?", options: ["감소하다", "늘다", "오르다", "상승"], answer: 0 },
        { q: "What is the synonym of 준비하다 (prepare)?", options: ["마련하다", "없애다", "버리다", "끝내다"], answer: 0 },
        { q: "What is the synonym of 채용하다 (hire, employ)?", options: ["고용하다", "해고하다", "자르다", "그만두다"], answer: 0 },
        { q: "What is the antonym of 채용하다 (hire)?", options: ["해고하다", "고용하다", "뽑다", "모집"], answer: 0 },
        { q: "What is the synonym of 제작하다 (manufacture)?", options: ["생산하다", "부수다", "파괴하다", "고치다"], answer: 0 },
        { q: "What is the antonym of 제작하다 (manufacture)?", options: ["부수다", "생산하다", "만들다", "조립"], answer: 0 },
        { q: "What is the synonym of 주문하다 (order)?", options: ["명령하다", "답다", "취소하다", "빼다"], answer: 0 },
        { q: "What is the synonym of 보관하다 (keep, store)?", options: ["저장하다", "버리다", "잃다", "찾다"], answer: 0 },
        { q: "What is the antonym of 보관하다 (store)?", options: ["꺼내다", "저장", "간직", "보존"], answer: 0 },
        { q: "What is the synonym of 정리하다 (arrange, organize)?", options: ["정돈하다", "어지럽히다", "흐트러뜨리다", "망치다"], answer: 0 },
        { q: "What is the antonym of 정리하다 (organize)?", options: ["어지럽히다", "정돈", "치우다", "청소"], answer: 0 },
        { q: "What is the synonym of 찾다 (look for, find)?", options: ["구하다", "잃어버리다", "숨기다", "놓치다"], answer: 0 },
        { q: "What is the antonym of 찾다 (find)?", options: ["잃어버리다", "구하다", "수색", "발견"], answer: 0 },
        { q: "What is the synonym of 보수하다 (repair)?", options: ["수리하다", "망치다", "파손하다", "부수다"], answer: 0 },
        { q: "What is the synonym of 만들다 (make, open)?", options: ["개설하다", "닫다", "폐쇄하다", "부수다"], answer: 0 },
        { q: "What is the antonym of 만들다/열다 (open)?", options: ["닫다", "개설", "생성", "출발"], answer: 0 },
        { q: "What is the synonym of 끄다 (turn off)?", options: ["차단하다", "켜다", "열다", "잇다"], answer: 0 },
        { q: "What is the antonym of 끄다 (turn off)?", options: ["켜다", "차단", "정지", "종료"], answer: 0 },
        { q: "What is the synonym of 받다 (receive) - action variant?", options: ["수령하다", "주다", "내리다", "빼다"], answer: 0 },
        { q: "What is the synonym of 보내다 (send)?", options: ["발송하다", "받다", "얻다", "쥐다"], answer: 0 },
        { q: "What is the antonym of 보내다 (send)?", options: ["받다", "발송", "전송", "부치다"], answer: 0 },
        { q: "What is the synonym of 포장하다 (wrap)?", options: ["싸다", "풀다", "뜯다", "해체하다"], answer: 0 },
        { q: "What is the antonym of 포장하다 (wrap)?", options: ["풀다", "싸다", "묶다", "포장"], answer: 0 },
        { q: "What is the synonym of 올라가다 (go up)?", options: ["상승하다", "내려가다", "떨어지다", "추락하다"], answer: 0 },
        { q: "What is the antonym of 올라가다 (go up)?", options: ["내려가다", "상승하다", "오르기", "등산"], answer: 0 },
        { q: "What is the synonym of 도착하다 (arrive)?", options: ["이르다", "출발하다", "떠나다", "가다"], answer: 0 },
        { q: "What is the antonym of 도착하다 (arrive)?", options: ["출발하다", "이르다", "도착", "골인"], answer: 0 },
        { q: "What is the synonym of 하차하다 (get off)?", options: ["내리다", "타다", "탑승하다", "오르다"], answer: 0 },
        { q: "What is the antonym of 하차하다 (get off)?", options: ["탑승하다", "내리다", "하차", "탈출"], answer: 0 },
        { q: "Synonym check: What word means the same as '받다'?", options: ["타다", "주다", "버리다", "밀다"], answer: 0 },
        { q: "Antonym check: What is the opposite of '받다'?", options: ["주다", "타다", "얻다", "수령"], answer: 0 },
        { q: "Synonym check: What word means the same as '바꾸다'?", options: ["교환하다", "지키다", "버리다", "찾다"], answer: 0 },
        { q: "Synonym check: What word means the same as '시작하다'?", options: ["출발하다", "끝내다", "마치다", "닫다"], answer: 0 },
        { q: "Antonym check: What is the opposite of '시작하다'?", options: ["끝내다", "출발하다", "시작", "오픈"], answer: 0 },
        { q: "Synonym check: What word means the same as '끝내다'?", options: ["마치다", "시작하다", "열다", "만들다"], answer: 0 },
        { q: "Synonym check: What word means the same as '팔다'?", options: ["판매하다", "사다", "구입하다", "얻다"], answer: 0 },
        { q: "Antonym check: What is the opposite of '팔다'?", options: ["사다", "판매하다", "수출", "제작"], answer: 0 },
        { q: "Synonym check: What word means the same as '사다'?", options: ["구입하다", "팔다", "버리다", "주다"], answer: 0 },
        { q: "Synonym check: What word means the same as '올리다'?", options: ["상승하다", "내리다", "떨어지다", "줄이다"], answer: 0 },
        { q: "Antonym check: What is the opposite of '올리다'?", options: ["내리다", "상승하다", "증가", "성장"], answer: 0 },
        { q: "Synonym check: What word means the same as '뽑다'?", options: ["빼내다", "꽂다", "넣다", "닫다"], answer: 0 },
        { q: "Antonym check: What is the opposite of '뽑다'?", options: ["꽂다", "빼내다", "당기다", "선택"], answer: 0 },
        { q: "Synonym check: What word means the same as '입금하다'?", options: ["돈을 넣다", "출금하다", "찾다", "쓰다"], answer: 0 },
        { q: "Antonym check: What is the opposite of '입금하다'?", options: ["출금하다", "넣다", "예금", "저축"], answer: 0 },
        { q: "Synonym check: What word means the same as '지키다'?", options: ["준수하다", "어기다", "위반하다", "버리다"], answer: 0 },
        { q: "Antonym check: What is the opposite of '지키다'?", options: ["어기다", "준수하다", "보호", "엄수"], answer: 0 },
        { q: "Synonym check: What word means the same as '환영하다'?", options: ["맞이하다", "환송하다", "배웅하다", "떠나다"], answer: 0 },
        { q: "Antonym check: What is the opposite of '환영하다'?", options: ["환송하다", "맞이하다", "영접", "반김"], answer: 0 },
        { q: "Synonym check: What word means the same as '옮기다'?", options: ["이동하다", "머무다", "멈추다", "정지"], answer: 0 },
        { q: "Antonym check: What is the opposite of '옮기다'?", options: ["머무다", "이동하다", "운반", "전달"], answer: 0 },
        { q: "Synonym check: What word means the same as '짓다'?", options: ["건설하다", "부수다", "파괴하다", "해지"], answer: 0 },
        { q: "Antonym check: What is the opposite of '짓다'?", options: ["부수다", "건설하다", "만들다", "생산"], answer: 0 },
        { q: "Synonym check: What word means the same as '출근하다'?", options: ["회사에 가다", "퇴근하다", "결근하다", "쉬다"], answer: 0 },
        { q: "Antonym check: What is the opposite of '출근하다'?", options: ["퇴근하다", "회사에 가다", "근무", "지각"], answer: 0 },
        { q: "Synonym check: What word means the same as '고르다'?", options: ["선택하다", "제외하다", "버리다", "무시"], answer: 0 },
        { q: "Antonym check: What is the opposite of '고르다'?", options: ["제외하다", "선택하다", "고름", "발탁"], answer: 0 },
        { q: "Synonym check: What word means the same as '버리다'?", options: ["폐기하다", "줍다", "간직하다", "저장"], answer: 0 },
        { q: "Antonym check: What is the opposite of '버리다'?", options: ["줍다", "폐기하다", "투기", "삭제"], answer: 0 },
        { q: "Synonym check: What word means the same as '수입하다'?", options: ["들여오다", "수출하다", "내보내다", "배송"], answer: 0 },
        { q: "Antonym check: What is the opposite of '수입하다'?", options: ["수출하다", "들여오다", "수입", "반입"], answer: 0 },
        { q: "Synonym check: What word means the same as '증가하다'?", options: ["늘다", "줄다", "감소", "축소"], answer: 0 },
        { q: "Antonym check: What is the opposite of '증가하다'?", options: ["감소하다", "늘다", "확대", "상승"], answer: 0 },
        { q: "Synonym check: What word means the same as '준비하다'?", options: ["마련하다", "해제하다", "폐기하다", "중단"], answer: 0 },
        { q: "Synonym check: What word means the same as '채용하다'?", options: ["고용하다", "해고하다", "자르다", "퇴사"], answer: 0 },
        { q: "Antonym check: What is the opposite of '채용하다'?", options: ["해고하다", "고용하다", "모집", "선발"], answer: 0 },
        { q: "Synonym check: What word means the same as '제작하다'?", options: ["생산하다", "파괴하다", "부수다", "철거"], answer: 0 },
        { q: "Antonym check: What is the opposite of '제작하다'?", options: ["파괴하다", "생산하다", "제조", "완성"], answer: 0 },
        { q: "Synonym check: What word means the same as '주문하다'?", options: ["주문", "취소", "환불", "반품"], answer: 0 },
        { q: "Synonym check: What word means the same as '보관하다'?", options: ["저장하다", "버리다", "분실", "방치"], answer: 0 },
        { q: "Antonym check: What is the opposite of '보관하다'?", options: ["꺼내다", "저장하다", "보존", "유지"], answer: 0 },
        { q: "Synonym check: What word means the same as '정리하다'?", options: ["정돈하다", "어지럽히다", "혼란", "방해"], answer: 0 },
        { q: "Antonym check: What is the opposite of '정리하다'?", options: ["어지럽히다", "정돈하다", "정돈", "정리"], answer: 0 },
        { q: "Synonym check: What word means the same as '찾다'?", options: ["구하다", "잃다", "놓치다", "숨기다"], answer: 0 },
        { q: "Antonym check: What is the opposite of '찾다'?", options: ["잃어버리다", "구하다", "탐색", "발견"], answer: 0 },
        { q: "Synonym check: What word means the same as '보수하다'?", options: ["수리하다", "망치다", "파손", "고장"], answer: 0 },
        { q: "Synonym check: What word means the same as '만들다'?", options: ["개설하다", "폐쇄하다", "중단", "철수"], answer: 0 },
        { q: "Antonym check: What is the opposite of '만들다'?", options: ["부수다", "개설하다", "생성", "구축"], answer: 0 },
        { q: "Synonym check: What word means the same as '끄다'?", options: ["차단하다", "켜다", "작동", "운행"], answer: 0 },
        { q: "Antonym check: What is the opposite of '끄다'?", options: ["켜다", "차단하다", "소등", "절전"], answer: 0 },
        { q: "Synonym check: What word means the same as '보내다'?", options: ["발송하다", "받다", "수령", "취득"], answer: 0 },
        { q: "Antonym check: What is the opposite of '보내다'?", options: ["받다", "발송하다", "전송", "송부"], answer: 0 },
        { q: "Synonym check: What word means the same as '포장하다'?", options: ["싸다", "풀다", "해체", "개봉"], answer: 0 },
        { q: "Antonym check: What is the opposite of '포장하다'?", options: ["풀다", "싸다", "포장", "밀봉"], answer: 0 },
        { q: "Synonym check: What word means the same as '올라가다'?", options: ["상승하다", "내려가다", "추락", "낙하"], answer: 0 },
        { q: "Antonym check: What is the opposite of '올라가다'?", options: ["내려가다", "상승하다", "등반", "상향"], answer: 0 },
        { q: "Synonym check: What word means the same as '도착하다'?", options: ["이르다", "출발하다", "떠나다", "시작"], answer: 0 },
        { q: "Antonym check: What is the opposite of '도착하다'?", options: ["출발하다", "이르다", "도착", "골인"], answer: 0 },
        { q: "Synonym check: What word means the same as '하차하다'?", options: ["내리다", "타다", "탑승", "승차"], answer: 0 },
        { q: "Antonym check: What is the opposite of '하차하다'?", options: ["탑승하다", "내리다", "하차", "하강"], answer: 0 }
    ]
};
