window.allExams = window.allExams || {};
window.allExams["exam6"] = {
    id: "exam6",
    title: "Korean Vocabulary: Noun to Verbs & Adjectives (100 Items)",
    description: "Comprehensive exam testing verbs and adjectives associated with specific nouns (actions, states, properties) based on study modules.",
    questions: [
        { q: "What verb/adjective matches 난로, 스위치, 선풍기, 휴대전화?", options: ["켜다/끄다", "보디", "캐다", "신청하다"], answer: 0 },
        { q: "What verb matches 시험, 면접, 텔레비전, 콘서트, 영화?", options: ["보다", "타다", "따다", "치다"], answer: 0 },
        { q: "What verb matches 감자, 고구마?", options: ["캐다", "타다", "짓다", "뽑다"], answer: 0 },
        { q: "What adjective matches 감정 (Emotions)?", options: ["기쁘다, 슬프다, 화나다, 무섭다, 불안하다", "가볍다, 무겁다", "가깝다, 멀다", "짧다, 길다"], answer: 0 },
        { q: "What verb matches 비자, 여권, 휴가, 보험금?", options: ["신청하다", "지키다", "돌리다", "따다"], answer: 0 },
        { q: "What verb matches 법, 규칙, 약속, 예의?", options: ["지키다", "신청하다", "뽑다", "깎다"], answer: 0 },
        { q: "What adjective matches 무게 (Weight)?", options: ["가볍다, 무겁다", "가깝다, 멀다", "짧다, 길다", "기쁘다, 슬프다"], answer: 0 },
        { q: "What adjective matches 거리 (Distance)?", options: ["가깝다, 멀다", "가볍다, 무겁다", "짧다, 길다", "화나다, 무섭다"], answer: 0 },
        { q: "What adjective matches 길이 (Length)?", options: ["짧다, 길다", "가깝다, 멀다", "가볍다, 무겁다", "기쁘다, 슬프다"], answer: 0 },
        { q: "What verb matches 집, 밥, 미소, 농사, 건물?", options: ["짓다", "타다", "따다", "치다"], answer: 0 },
        { q: "What verb matches 세탁기, 고개, 허리, 청소기?", options: ["돌리다", "타다", "따다", "치다"], answer: 0 },
        { q: "What verb matches 자격증, 사과, 고추, 버섯?", options: ["따다", "타다", "치다", "뽑다"], answer: 0 },
        { q: "What verb matches 지하철, 월급, 커피?", options: ["타다", "따다", "치다", "짓다"], answer: 0 },
        { q: "What verb matches 테니스, 번개, 농약, 텐트, 그물, 기타?", options: ["치다", "타다", "따다", "뽑다"], answer: 0 },
        { q: "What verb matches 카드, 번호표, 플러그?", options: ["뽑다", "치다", "타다", "따다"], answer: 0 },
        { q: "What verb matches 치우다?", options: ["방, 쓰레기 (Room, Trash)", "사과, 머리", "오해, 스트레스", "비자, 여권"], answer: 0 },
        { q: "What verb matches 풀다?", options: ["오해, 스트레스, 문제, 네크타이", "집, 밥, 미소", "지하철, 월급", "자격증, 사과"], answer: 0 },
        { q: "What verb matches 깎다?", options: ["가격, 연필, 사과, 머리", "카드, 번호표", "방, 쓰레기", "법, 규칙"], answer: 0 },
        { q: "Which verbs are associated with 난로, 스위치, 선풍기, 휴대전화?", options: ["켜다, 끄다", "보다, 듣다", "타다, 내리다", "따다, 심다"], answer: 0 },
        { q: "Which verb is associated with 시험, 면접, 영화?", options: ["보다", "캐다", "짓다", "뽑다"], answer: 0 },
        { q: "Which verb is associated with 감자, 고구마?", options: ["캐다", "보다", "타다", "치다"], answer: 0 },
        { q: "Which adjectives describe 감정 (Emotions)?", options: ["기쁘다, 슬프다, 화나다", "가볍다, 무겁다", "가깝다, 멀다", "짧다, 길다"], answer: 0 },
        { q: "Which verb is associated with 비자, 여권, 보험금?", options: ["신청하다", "지키다", "돌리다", "치다"], answer: 0 },
        { q: "Which verb is associated with 법, 규칙, 약속?", options: ["지키다", "신청하다", "타다", "따다"], answer: 0 },
        { q: "Which adjectives describe 무게 (Weight)?", options: ["가볍다, 무겁다", "짧다, 길다", "가깝다, 멀다", "기쁘다, 슬프다"], answer: 0 },
        { q: "Which adjectives describe 거리 (Distance)?", options: ["가깝다, 멀다", "가볍다, 무겁다", "짧다, 길다", "화나다, 무섭다"], answer: 0 },
        { q: "Which adjectives describe 길이 (Length)?", options: ["짧다, 길다", "가깝다, 멀다", "가볍다, 무겁다", "기쁘다, 슬프다"], answer: 0 },
        { q: "Which verb is associated with 집, 밥, 미소, 건물?", options: ["짓다", "타다", "따다", "뽑다"], answer: 0 },
        { q: "Which verb is associated with 세탁기, 고개, 허리?", options: ["돌리다", "따다", "치다", "짓다"], answer: 0 },
        { q: "Which verb is associated with 자격증, 사과, 버섯?", options: ["따다", "타다", "치다", "뽑다"], answer: 0 },
        { q: "Which verb is associated with 지하철, 월급, 커피?", options: ["타다", "따다", "치다", "짓다"], answer: 0 },
        { q: "Which verb is associated with 테니스, 번개, 농약?", options: ["치다", "타다", "따다", "뽑다"], answer: 0 },
        { q: "Which verb is associated with 카드, 번호표, 플러그?", options: ["뽑다", "치다", "타다", "따다"], answer: 0 },
        { q: "Which verb is associated with 쓰레기, 방?", options: ["치우다", "풀다", "깎다", "캐다"], answer: 0 },
        { q: "Which verb is associated with 오해, 스트레스, 문제?", options: ["풀다", "치우다", "깎다", "짓다"], answer: 0 },
        { q: "Which verb is associated with 가격, 연필, 사과, 머리?", options: ["깎다", "뽑다", "타다", "지키다"], answer: 0 },
        { q: "Match action: What do you do with '난로' or '스위치'?", options: ["켜다/끄다", "보다", "캐다", "타다"], answer: 0 },
        { q: "Match action: What do you do with '시험' or '면접'?", options: ["보다", "짓다", "돌리다", "따다"], answer: 0 },
        { q: "Match action: What do you do with '감자'?", options: ["캐다", "타다", "치다", "뽑다"], answer: 0 },
        { q: "Match action: What do you do with '비자' or '여권'?", options: ["신청하다", "지키다", "돌리다", "풀다"], answer: 0 },
        { q: "Match action: What do you do with '법' or '규칙'?", options: ["지키다", "신청하다", "타다", "따다"], answer: 0 },
        { q: "Match action: What do you do with '밥' or '집'?", options: ["짓다", "돌리다", "타다", "치다"], answer: 0 },
        { q: "Match action: What do you do with '세탁기'?", options: ["돌리다", "따다", "치다", "뽑다"], answer: 0 },
        { q: "Match action: What do you do with '자격증'?", options: ["따다", "타다", "치다", "짓다"], answer: 0 },
        { q: "Match action: What do you do with '지하철' or '월급'?", options: ["타다", "따다", "치다", "뽑다"], answer: 0 },
        { q: "Match action: What do you do with '테니스' or '번개'?", options: ["치다", "타다", "따다", "짓다"], answer: 0 },
        { q: "Match action: What do you do with '번호표' or '플러그'?", options: ["뽑다", "치다", "타다", "따다"], answer: 0 },
        { q: "Match action: What do you do with '쓰레기'?", options: ["치우다", "풀다", "깎다", "캐다"], answer: 0 },
        { q: "Match action: What do you do with '스트레스' or '문제'?", options: ["풀다", "치우다", "깎다", "지키다"], answer: 0 },
        { q: "Match action: What do you do with '가격' or '연필'?", options: ["깎다", "뽑다", "타다", "따다"], answer: 0 },
        { q: "Select the correct adjective for '무게' (Weight):", options: ["가볍다, 무겁다", "가깝다, 멀다", "짧다, 길다", "기쁘다, 슬프다"], answer: 0 },
        { q: "Select the correct adjective for '거리' (Distance):", options: ["가깝다, 멀다", "가볍다, 무겁다", "짧다, 길다", "화나다, 무섭다"], answer: 0 },
        { q: "Select the correct adjective for '길이' (Length):", options: ["짧다, 길다", "가깝다, 멀다", "가볍다, 무겁다", "기쁘다, 슬프다"], answer: 0 },
        { q: "Select the correct adjective group for '감정' (Emotions):", options: ["기쁘다, 슬프다, 화나다, 무섭다", "가볍다, 무겁다", "가깝다, 멀다", "짧다, 길다"], answer: 0 },
        { q: "Which combination correctly matches '집, 밥, 미소'?", options: ["짓다", "타다", "따다", "치다"], answer: 0 },
        { q: "Which combination correctly matches '사과, 고추, 버섯'?", options: ["따다", "타다", "치다", "짓다"], answer: 0 },
        { q: "Which combination correctly matches '월급, 커피, 지하철'?", options: ["타다", "따다", "치다", "뽑다"], answer: 0 },
        { q: "Which combination correctly matches '테니스, 그물, 기타'?", options: ["치다", "타다", "따다", "짓다"], answer: 0 },
        { q: "Which combination correctly matches '카드, 플러그'?", options: ["뽑다", "치다", "타다", "따다"], answer: 0 },
        { q: "Which combination correctly matches '쓰레기, 방'?", options: ["치우다", "풀다", "깎다", "캐다"], answer: 0 },
        { q: "Which combination correctly matches '오해, 문제'?", options: ["풀다", "치우다", "깎다", "짓다"], answer: 0 },
        { q: "Which combination correctly matches '머리, 사과, 연필'?", options: ["깎다", "뽑다", "타다", "따다"], answer: 0 },
        { q: "What is the primary action for '선풍기' or '스위치'?", options: ["켜다/끄다", "보다", "캐다", "타다"], answer: 0 },
        { q: "What is the primary action for '면접' or '콘서트'?", options: ["보다", "짓다", "돌리다", "따다"], answer: 0 },
        { q: "What is the primary action for '고구마'?", options: ["캐다", "타다", "치다", "뽑다"], answer: 0 },
        { q: "What is the primary action for '휴가' or '보험금'?", options: ["신청하다", "지키다", "돌리다", "풀다"], answer: 0 },
        { q: "What is the primary action for '약속' or '예의'?", options: ["지키다", "신청하다", "타다", "따다"], answer: 0 },
        { q: "What action is paired with '고개' or '허리'?", options: ["돌리다", "따다", "치다", "짓다"], answer: 0 },
        { q: "What action is paired with '농약' or '텐트'?", options: ["치다", "타다", "따다", "뽑다"], answer: 0 },
        { q: "What action is paired with '번호표'?", options: ["뽑다", "치다", "타다", "따다"], answer: 0 },
        { q: "What action is paired with '방' (room cleaning)?", options: ["치우다", "풀다", "깎다", "캐다"], answer: 0 },
        { q: "What action is paired with '넥타이'?", options: ["풀다", "치우다", "깎다", "짓다"], answer: 0 },
        { q: "What action is paired with '가격'?", options: ["깎다", "뽑다", "타다", "따다"], answer: 0 },
        { q: "Which verb matches '텔레비전'?", options: ["보다", "캐다", "짓다", "뽑다"], answer: 0 },
        { q: "Which verb matches '감자'?", options: ["캐다", "보다", "타다", "치다"], answer: 0 },
        { q: "Which verb matches '비자'?", options: ["신청하다", "지키다", "돌리다", "치다"], answer: 0 },
        { q: "Which verb matches '법'?", options: ["지키다", "신청하다", "타다", "따다"], answer: 0 },
        { q: "Which verb matches '밥'?", options: ["짓다", "타다", "따다", "뽑다"], answer: 0 },
        { q: "Which verb matches '세탁기'?", options: ["돌리다", "따다", "치다", "짓다"], answer: 0 },
        { q: "Which verb matches '자격증'?", options: ["따다", "타다", "치다", "뽑다"], answer: 0 },
        { q: "Which verb matches '지하철'?", options: ["타다", "따다", "치다", "짓다"], answer: 0 },
        { q: "Which verb matches '테니스'?", options: ["치다", "타다", "따다", "뽑다"], answer: 0 },
        { q: "Which verb matches '카드'?", options: ["뽑다", "치다", "타다", "따다"], answer: 0 },
        { q: "Which verb matches '쓰레기'?", options: ["치우다", "풀다", "깎다", "캐다"], answer: 0 },
        { q: "Which verb matches '스트레스'?", options: ["풀다", "치우다", "깎다", "짓다"], answer: 0 },
        { q: "Which verb matches '가격'?", options: ["깎다", "뽑다", "타다", "따다"], answer: 0 },
        { q: "Which adjective matches '무게'?", options: ["가볍다, 무겁다", "가깝다, 멀다", "짧다, 길다", "기쁘다, 슬프다"], answer: 0 },
        { q: "Which adjective matches '거리'?", options: ["가깝다, 멀다", "가볍다, 무겁다", "짧다, 길다", "화나다, 무섭다"], answer: 0 },
        { q: "Which adjective matches '길이'?", options: ["짧다, 길다", "가깝다, 멀다", "가볍다, 무겁다", "기쁘다, 슬프다"], answer: 0 },
        { q: "Which adjective matches '감정'?", options: ["기쁘다, 슬프다, 화나다", "가볍다, 무겁다", "가깝다, 멀다", "짧다, 길다"], answer: 0 },
        { q: "Select the match for '선풍기':", options: ["켜다/끄다", "보다", "캐다", "타다"], answer: 0 },
        { q: "Select the match for '면접':", options: ["보다", "짓다", "돌리다", "따다"], answer: 0 },
        { q: "Select the match for '고구마':", options: ["캐다", "타다", "치다", "뽑다"], answer: 0 },
        { q: "Select the match for '여권':", options: ["신청하다", "지키다", "돌리다", "풀다"], answer: 0 },
        { q: "Select the match for '약속':", options: ["지키다", "신청하다", "타다", "따다"], answer: 0 },
        { q: "Select the match for '미소':", options: ["짓다", "돌리다", "타다", "치다"], answer: 0 },
        { q: "Select the match for '허리':", options: ["돌리다", "따다", "치다", "뽑다"], answer: 0 },
        { q: "Select the match for '사과' (harvest):", options: ["따다", "타다", "치다", "짓다"], answer: 0 },
        { q: "Select the match for '월급':", options: ["타다", "따다", "치다", "뽑다"], answer: 0 },
        { q: "Select the match for '농약':", options: ["치다", "타다", "따다", "짓다"], answer: 0 },
        { q: "Select the match for '플러그':", options: ["뽑다", "치다", "타다", "따다"], answer: 0 },
        { q: "Select the match for '방':", options: ["치우다", "풀다", "깎다", "캐다"], answer: 0 },
        { q: "Select the match for '오해':", options: ["풀다", "치우다", "깎다", "짓다"], answer: 0 },
        { q: "Select the match for '연필':", options: ["깎다", "뽑다", "타다", "따다"], answer: 0 }
    ]
};
