window.allExams = window.allExams || {};
window.allExams["exam9"] = {
    id: "exam9",
    title: "Adjective Synonyms & Antonyms",
    subtitle: "Advanced Practice Test",
    badge: "어휘 (Vocabulary)",
    description: "Advanced 150-item test covering descriptive adjectives, synonyms, and antonyms.",
    questions: [
        { q: "What is the synonym of 가깝다 (near)?", options: ["멀다", "가벼우다", "차갑다", "밝다"], answer: 0 },
        { q: "What is the antonym of 가깝다 (near)?", options: ["멀다", "가깝기", "근처", "이웃"], answer: 0 },
        { q: "What is the synonym of 무겁다 (heavy)?", options: ["가볍다", "가벼우다", "크다", "작다"], answer: 0 },
        { q: "What is the antonym of 무겁다 (heavy)?", options: ["가볍다", "무거움", "체중", "질량"], answer: 0 },
        { q: "What is the synonym of 차갑다 (cold - touch)?", options: ["춥다", "뜨겁다", "따뜻하다", "시원하다"], answer: 0 },
        { q: "What is the antonym of 차갑다 (cold)?", options: ["뜨겁다", "춥다", "시원하다", "차분하다"], answer: 0 },
        { q: "What is the synonym of 오래되다 (old - object)?", options: ["새롭다", "낡다", "젊다", "빠르다"], answer: 0 },
        { q: "What is the antonym of 오래되다 (old)?", options: ["새롭다", "낡다", "골동품", "세월"], answer: 0 },
        { q: "What is the synonym of 밝다 (bright)?", options: ["어둡다", "환하다", "깜깜하다", "흐리다"], answer: 1 },
        { q: "What is the antonym of 밝다 (bright)?", options: ["어둡다", "환하다", "빛나다", "햇살"], answer: 0 },
        { q: "What is the synonym of 어렵다 (difficult)?", options: ["곤란하다", "쉽다", "간단하다", "편안하다"], answer: 0 },
        { q: "What is the antonym of 어렵다 (difficult)?", options: ["쉽다", "곤란하다", "복잡하다", "힘들다"], answer: 0 },
        { q: "What is the synonym of 작다 (small)?", options: ["크다", "적다", "넓다", "길다"], answer: 1 },
        { q: "What is the antonym of 작다 (small)?", options: ["크다", "소형", "미니", "협소"], answer: 0 },
        { q: "What is the synonym of 불편하다 (uncomfortable)?", options: ["편안하다", "편하다", "좋다", "깨끗하다"], answer: 0 },
        { q: "What is the antonym of 불편하다 (uncomfortable)?", options: ["편안하다", "불편", "고생", "어려움"], answer: 0 },
        { q: "What is the synonym of 춥다 (cold - weather)?", options: ["덥다", "늘다", "시원하다", "따뜻하다"], answer: 0 },
        { q: "What is the antonym of 춥다 (cold)?", options: ["덥다", "추움", "겨울", "얼음"], answer: 0 },
        { q: "What is the synonym of 더럽다 (dirty)?", options: ["지저분하다", "깨끗하다", "맑다", "정리되다"], answer: 0 },
        { q: "What is the antonym of 더럽다 (dirty)?", options: ["깨끗하다", "지저분하다", "오염", "쓰레기"], answer: 0 },
        { q: "What is the synonym of 높다 (high)?", options: ["낮다", "크다", "길다", "깊다"], answer: 0 },
        { q: "What is the antonym of 높다 (high)?", options: ["낮다", "높이", "상층", "꼭대기"], answer: 0 },
        { q: "What is the synonym of 같다 (same)?", options: ["다르다", "비슷하다", "일치하다", "공통"], answer: 0 },
        { q: "What is the antonym of 같다 (same)?", options: ["다르다", "비슷하다", "동일", "일치"], answer: 0 },
        { q: "What is the synonym of 따뜻하다 (warm)?", options: ["시원하다", "춥다", "차갑다", "뜨겁다"], answer: 0 },
        { q: "What is the antonym of 따뜻하다 (warm)?", options: ["시원하다", "따뜻함", "온화", "봄"], answer: 0 },
        { q: "What is the synonym of 부지런하다 (diligent)?", options: ["게으르다", "부지런함", "열심", "노력"], answer: 0 },
        { q: "What is the antonym of 부지런하다 (diligent)?", options: ["게으르다", "나태하다", "부지런", "성실"], answer: 0 },
        { q: "What is the synonym of 조용하다 (quiet)?", options: ["시끄럽다", "고요하다", "잠잠하다", "평화롭다"], answer: 0 },
        { q: "What is the antonym of 조용하다 (quiet)?", options: ["시끄럽다", "고요하다", "잠잠", "적막"], answer: 0 },
        { q: "What is the synonym of 복잡하다 (complicated)?", options: ["단단하다", "단순하다", "쉽다", "편하다"], answer: 0 },
        { q: "What is the antonym of 복잡하다 (complicated)?", options: ["단순하다", "복잡", "혼란", "어려움"], answer: 0 },
        { q: "What is the synonym of 엄격하다 (strict)?", options: ["너그럽다", "자유롭다", "부드럽다", "편하다"], answer: 0 },
        { q: "What is the synonym of 좁다 (narrow)?", options: ["넓다", "크다", "길다", "많다"], answer: 0 },
        { q: "What is the antonym of 좁다 (narrow)?", options: ["넓다", "협소", "비좁다", "틈"], answer: 0 },
        { q: "What is the synonym of 얇다 (thin)?", options: ["두껍다", "가볍다", "작다", "가늘다"], answer: 0 },
        { q: "What is the antonym of 얇다 (thin)?", options: ["두껍다", "얇기", "종이", "두께"], answer: 0 },
        { q: "What is the synonym of 건조하다 (dry)?", options: ["습하다", "축축하다", "물기", "비"], answer: 0 },
        { q: "What is the antonym of 건조하다 (dry)?", options: ["습하다", "건조", "가뭄", "사막"], answer: 0 },
        { q: "What is the synonym of 가난하다 (poor)?", options: ["부유하다", "풍요롭다", "돈많다", "거지"], answer: 0 },
        { q: "What is the antonym of 가난하다 (poor)?", options: ["부유하다", "가난", "빈곤", "결핍"], answer: 0 },
        { q: "What is the synonym of 부드럽다 (soft)?", options: ["딱딱하다", "단단하다", "거칠다", "부드러움"], answer: 0 },
        { q: "What is the antonym of 부드럽다 (soft)?", options: ["딱딱하다", "부드러움", "솜", "크림"], answer: 0 },
        { q: "What is the synonym of 크다 (big)?", options: ["작다", "넓다", "거대하다", "높다"], answer: 2 },
        { q: "What is the antonym of 크다 (big)?", options: ["작다", "크기", "거대", "장대"], answer: 0 },
        { q: "What is the synonym of 길다 (long)?", options: ["짧다", "높다", "넓다", "멀다"], answer: 0 },
        { q: "What is the antonym of 길다 (long)?", options: ["짧다", "길이", "연장", "영원"], answer: 0 },
        { q: "What is the synonym of 빠르다 (fast)?", options: ["느리다", "급하다", "신속하다", "즉시"], answer: 0 },
        { q: "What is the antonym of 빠르다 (fast)?", options: ["느리다", "속도", "스피드", "질주"], answer: 0 },
        { q: "What is the synonym of 많다 (many)?", options: ["적다", "풍부하다", "가득", "충분"], answer: 0 },
        { q: "What is the antonym of 많다 (many)?", options: ["적다", "많음", "대량", "수많음"], answer: 0 },
        { q: "What is the synonym of 무섭다 (scary)?", options: ["두렵다", "기쁘다", "슬프다", "안심"], answer: 0 },
        { q: "What is the antonym of 무섭다 (scary)?", options: ["안심하다", "두렵다", "공포", "떨림"], answer: 0 },
        { q: "What is the synonym of 슬프다 (sad)?", options: ["기쁘다", "괴롭다", "우울하다", "눈물"], answer: 0 },
        { q: "What is the antonym of 슬프다 (sad)?", options: ["기쁘다", "슬픔", "비극", "절망"], answer: 0 },
        { q: "What is the synonym of 안전하다 (safe)?", options: ["위험하다", "안심", "평화", "보호"], answer: 0 },
        { q: "What is the antonym of 안전하다 (safe)?", options: ["위험하다", "안전", "무사", "평온"], answer: 0 },
        { q: "Synonym check: What word means the same as '가깝다'?", options: ["멀다", "가깝고", "근처", "이웃"], answer: 0 },
        { q: "Antonym check: What is the opposite of '가깝다'?", options: ["멀다", "가깝다", "가까움", "근접"], answer: 0 },
        { q: "Synonym check: What word means the same as '무겁다'?", options: ["가볍다", "무거움", "체중", "중량"], answer: 0 },
        { q: "Antonym check: What is the opposite of '무겁다'?", options: ["가볍다", "무겁다", "중후", "묵직"], answer: 0 },
        { q: "Synonym check: What word means the same as '차갑다'?", options: ["뜨겁다", "춥다", "시원", "냉기"], answer: 0 },
        { q: "Antonym check: What is the opposite of '차갑다'?", options: ["뜨겁다", "차갑다", "냉랭", "서늘"], answer: 0 },
        { q: "Synonym check: What word means the same as '오래되다'?", options: ["새롭다", "낡다", "골동", "세월"], answer: 0 },
        { q: "Antonym check: What is the opposite of '오래되다'?", options: ["새롭다", "오래되다", "구식", "헌것"], answer: 0 },
        { q: "Synonym check: What word means the same as '밝다'?", options: ["어둡다", "환하다", "빛남", "명랑"], answer: 1 },
        { q: "Antonym check: What is the opposite of '밝다'?", options: ["어둡다", "밝다", "환함", "명백"], answer: 0 },
        { q: "Synonym check: What word means the same as '어렵다'?", options: ["쉽다", "곤란하다", "난해", "복잡"], answer: 0 },
        { q: "Antonym check: What is the opposite of '어렵다'?", options: ["쉽다", "어렵다", "곤란", "난관"], answer: 0 },
        { q: "Synonym check: What word means the same as '작다'?", options: ["크다", "적다", "소형", "미니"], answer: 1 },
        { q: "Antonym check: What is the opposite of '작다'?", options: ["크다", "작다", "소량", "미소"], answer: 0 },
        { q: "Synonym check: What word means the same as '불편하다'?", options: ["편안하다", "편하다", "좋음", "안락"], answer: 0 },
        { q: "Antonym check: What is the opposite of '불편하다'?", options: ["편안하다", "불편하다", "고통", "난처"], answer: 0 },
        { q: "Synonym check: What word means the same as '춥다'?", options: ["덥다", "추움", "동파", "서리"], answer: 0 },
        { q: "Antonym check: What is the opposite of '춥다'?", options: ["덥다", "춥다", "한파", "추위"], answer: 0 },
        { q: "Synonym check: What word means the same as '더럽다'?", options: ["깨끗하다", "지저분하다", "오염", "티끌"], answer: 0 },
        { q: "Antonym check: What is the opposite of '더럽다'?", options: ["깨끗하다", "더럽다", "추잡", "불결"], answer: 0 },
        { q: "Synonym check: What word means the same as '높다'?", options: ["낮다", "높이", "상층", "꼭대기"], answer: 0 },
        { q: "Antonym check: What is the opposite of '높다'?", options: ["낮다", "높다", "고층", "정상"], answer: 0 },
        { q: "Synonym check: What word means the same as '같다'?", options: ["다르다", "비슷하다", "일치", "동일"], answer: 0 },
        { q: "Antonym check: What is the opposite of '같다'?", options: ["다르다", "같다", "유사", "공통"], answer: 0 },
        { q: "Synonym check: What word means the same as '따뜻하다'?", options: ["시원하다", "따뜻함", "온화", "봄"], answer: 0 },
        { q: "Antonym check: What is the opposite of '따뜻하다'?", options: ["시원하다", "따뜻하다", "온열", "난방"], answer: 0 },
        { q: "Synonym check: What word means the same as '부지런하다'?", options: ["게으르다", "부지런", "열심", "성실"], answer: 0 },
        { q: "Antonym check: What is the opposite of '부지런하다'?", options: ["게으르다", "부지런하다", "나태", "태만"], answer: 0 },
        { q: "Synonym check: What word means the same as '조용하다'?", options: ["시끄럽다", "고요하다", "잠잠", "적막"], answer: 0 },
        { q: "Antonym check: What is the opposite of '조용하다'?", options: ["시끄럽다", "조용하다", "침묵", "음소거"], answer: 0 },
        { q: "Synonym check: What word means the same as '복잡하다'?", options: ["단순하다", "복잡", "혼란", "어려움"], answer: 0 },
        { q: "Antonym check: What is the opposite of '복잡하다'?", options: ["단순하다", "복잡하다", "엉킴", "미로"], answer: 0 },
        { q: "Synonym check: What word means the same as '엄격하다'?", options: ["너그럽다", "자유롭다", "부드럽다", "엄숙"], answer: 0 },
        { q: "Synonym check: What word means the same as '좁다'?", options: ["넓다", "협소", "비좁다", "틈"], answer: 0 },
        { q: "Antonym check: What is the opposite of '좁다'?", options: ["넓다", "좁다", "협소함", "공간"], answer: 0 },
        { q: "Synonym check: What word means the same as '얇다'?", options: ["두껍다", "얇기", "종이", "두께"], answer: 0 },
        { q: "Antonym check: What is the opposite of '얇다'?", options: ["두껍다", "얇다", "실", "종이장"], answer: 0 },
        { q: "Synonym check: What word means the same as '건조하다'?", options: ["습하다", "건조", "가뭄", "사막"], answer: 0 },
        { q: "Antonym check: What is the opposite of '건조하다'?", options: ["습하다", "건조하다", "바짝", "메마름"], answer: 0 },
        { q: "Synonym check: What word means the same as '가난하다'?", options: ["부유하다", "가난", "빈곤", "결핍"], answer: 0 },
        { q: "Antonym check: What is the opposite of '가난하다'?", options: ["부유하다", "가난하다", "거지", "결핍"], answer: 0 },
        { q: "Synonym check: What word means the same as '부드럽다'?", options: ["딱딱하다", "부드러움", "솜", "크림"], answer: 0 },
        { q: "Antonym check: What is the opposite of '부드럽다'?", options: ["딱딱하다", "부드럽다", "유연", "순함"], answer: 0 },
        { q: "Synonym check: What word means the same as '크다'?", options: ["작다", "크기", "거대", "장대"], answer: 2 },
        { q: "Antonym check: What is the opposite of '크다'?", options: ["작다", "크다", "거대함", "광대"], answer: 0 },
        { q: "Synonym check: What word means the same as '길다'?", options: ["짧다", "길이", "연장", "영원"], answer: 0 },
        { q: "Antonym check: What is the opposite of '길다'?", options: ["짧다", "길다", "단축", "백년"], answer: 0 },
        { q: "Synonym check: What word means the same as '빠르다'?", options: ["느리다", "속도", "스피드", "질주"], answer: 0 },
        { q: "Antonym check: What is the opposite of '빠르다'?", options: ["느리다", "빠르다", "급행", "특급"], answer: 0 },
        { q: "Synonym check: What word means the same as '많다'?", options: ["적다", "많음", "대량", "수많음"], answer: 0 },
        { q: "Antonym check: What is the opposite of '많다'?", options: ["적다", "많다", "풍족", "가득"], answer: 0 },
        { q: "Synonym check: What word means the same as '무섭다'?", options: ["두렵다", "기쁘다", "슬프다", "공포"], answer: 0 },
        { q: "Antonym check: What is the opposite of '무섭다'?", options: ["안심하다", "무섭다", "공포심", "두려움"], answer: 0 },
        { q: "Synonym check: What word means the same as '슬프다'?", options: ["기쁘다", "슬픔", "비극", "절망"], answer: 0 },
        { q: "Antonym check: What is the opposite of '슬프다'?", options: ["기쁘다", "슬프다", "눈물", "오열"], answer: 0 },
        { q: "Synonym check: What word means the same as '안전하다'?", options: ["위험하다", "안전", "무사", "평온"], answer: 0 },
        { q: "Antonym check: What is the opposite of '안전하다'?", options: ["위험하다", "안전하다", "보호", "구조"], answer: 0 }
    ]
};
